# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df8373da3bdbe1d9870c3a7d578ac47ace129b7054ca9ef92cb94036f0ffb9a457861f32f639a6524b3457a36b511a63ac8b06f35ed8fdc63c52490ffaf58de5

test:
  secret_key_base: 43ae9b33190589bd9fce7e37fd21cc052fe7eb868ad46a9c8f6eb42411d3f61fa49d24a872b8e41af1eb9eba7fee9a3a25596f11579def5bf6bba92220806db2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
